### ISSUE TITLE
Retrieve data from "create account" form in landing.html

### ISSUE THREAD

**Issue by lucsedirae** [lucsedirae/neighbors-in-need#21]

**Comment by MarkMajorUR** [comment]
![image](https://user-images.githubusercontent.com/67079405/100696966-c5023580-3362-11eb-8153-bf238b03bd75.png)

I found a method called .serialize() that takes in inputs from forms, and then puts them in one string. This string can be turned into a keyd array with .split('&')

![image](https://user-images.githubusercontent.com/67079405/100697075-05fa4a00-3363-11eb-8083-6e2447f2311c.png)
