### ISSUE TITLE
Integrate event info form into homescreenNIN.html

### ISSUE THREAD

**Issue by lucsedirae** [lucsedirae/neighbors-in-need#22]

**Comment by MarkMajorUR** [comment]
![image](https://user-images.githubusercontent.com/67079405/100699863-1235d580-336a-11eb-9978-9e79890cfc1a.png)

I added the form elements into homescreenNIN.html, Location, address, ect. are then put into a keyd array with the code below in homescreen.js
![image](https://user-images.githubusercontent.com/67079405/100700975-bc166180-336c-11eb-9434-c47891b6dd80.png)

Next step is to parse the data and send it to our database
